### ISSUE TITLE
Color issues

### ISSUE THREAD

**Issue by echosa** [arcticicestudio/nord-intellij-idea-syntax#10]
I've found two color issues. There may be more.

First, when looking at diffs, the right side of the diff (showing changes) is colored in a way that some text is unreadable. For instance, in this screenshot, you can't read the text I put inside the `var_dump`:

<img width="1268" alt="screen shot 2017-05-03 at 4 38 16 pm" src="https://cloud.githubusercontent.com/assets/133786/25682941/acce8cb0-301f-11e7-9cb3-aee0250d85fc.png">

Second, when you put the cursor in a method or variable name, it will highlight that name and other instances of it. This makes it easy to find all usages of a variable, for instance. However, when you double-click to actually select the text, the coloring is exactly the same! You can't tell when you've selected the text or not. Screenshot examples:

This method name just has the cursor in it, and has not bee selected:

<img width="304" alt="screen shot 2017-05-03 at 4 38 51 pm" src="https://cloud.githubusercontent.com/assets/133786/25683015/f0f2d13a-301f-11e7-88a7-f098042f5d5a.png">

This time, the method has been selected with a double-click:

<img width="304" alt="screen shot 2017-05-03 at 4 39 02 pm" src="https://cloud.githubusercontent.com/assets/133786/25683027/fc6e598a-301f-11e7-950d-42807f7f6a79.png">

**Comment by arcticicestudio** [comment]
Thanks for your report :+1: 
Sorry for my late reply, I've been busy with my job.

I've added this ticket to the [project board for the next version](https://github.com/arcticicestudio/nord-intellij-idea-syntax/projects/4). I've also already noticed the `diff` colors are too bright and lowered the opacity in some other projects. The next version will also include new features added to the new IntelliJ version 2017.1 and 2017.2.

**Comment by arcticicestudio** [comment]
@echosa Sorry again for the late response, I've had almost no freetime to work on my projects.

I've created the PRs #25 and #27 to improve the diff- and debugging background colors and the background of the identifier under the caret with a selection.

**Comment by arcticicestudio** [comment]
Superseded by #25 and #27.

**Comment by echosa** [comment]
Awesome! I look forward to those getting merged in and released so I can try this theme out again! :-)

**Comment by arcticicestudio** [comment]
🚢 Shipped with release version 🏷 [0.3.0](https://github.com/arcticicestudio/nord-intellij-idea-syntax/releases/tag/v0.3.0).
