### ISSUE TITLE
How to build jar file on windows

### ISSUE THREAD

**Issue by thimma11** [arcticicestudio/nord-intellij-idea-syntax#11]
How can i build the .jar file on windows? Because it doesn't seems to work for me using the build.sh script. Or is there a link where i can download the .jar file directly?

**Comment by arcticicestudio** [comment]
Well, I'm not a Windows user so I often forget to implement support for it 😆 
The `build.sh` is a script for UNIX based systems like Linux and OSX, it won't run on Windows for sure.
I'll implement a MSDOS `build.bat` to support Windows systems.

> Or is there a link where i can download the .jar file directly?

I've added pre-compiled artifacts to version 0.1.0, but forgot to include them for version 0.2.0. I'll add them tomorrow.

**Comment by arcticicestudio** [comment]
Forgot to notify you, sorry.
I've added the pre-compiled JARs to the [0.2.0](https://github.com/arcticicestudio/nord-intellij-idea-syntax/releases/tag/v0.2.0) release.

**Comment by arcticicestudio** [comment]
@thimma11 I've implemented a build script for Windows based OS which can be reviewed in #13.
