### ISSUE TITLE
0.2.0 pre-built .icls missing

### ISSUE THREAD

**Issue by rydgeback** [arcticicestudio/nord-intellij-idea-syntax#12]
I could only find the .icls file for 0.1.0, adding it for 0.2.0 would be appreciated.

**Comment by arcticicestudio** [comment]
You can check out the tag `v0.2.0` and [download the file](https://github.com/arcticicestudio/nord-intellij-idea-syntax/blob/v0.2.0/src/nord-intellij-idea-syntax.icls) anytime.
Anyway, I've added it to the release version [0.2.0](https://github.com/arcticicestudio/nord-intellij-idea-syntax/releases/tag/v0.2.0) including the pre-built JAR.
