### ISSUE TITLE
Everything is italicized 

### ISSUE THREAD

**Issue by echosa** [arcticicestudio/nord-intellij-idea-syntax#5]
I downloaded this theme (manual install) for IDEA. I work with PHP/Symfony2. The colors all look mostly right and good, but everything is italicized. The screenshots in the README aren't, so is there something off about the PHP settings that makes everything italicized? Do I need to just make a custom theme from this one and manually change that myself?

Correction: PHP and Twig are italicized. HTML, YML, JSON, and JavaScript are not.

**Comment by echosa** [comment]
New info: I looked into manually changing it, just to see if that would work. However, the "italicized" checkbox *isn't* checked for most of what is being shown in italics. I don't get it. For example:

<img width="1017" alt="image 2017-04-04 at 12 01 59 pm" src="https://cloud.githubusercontent.com/assets/133786/24669093/ab620aa8-192e-11e7-8d5d-b0c752ee9ac5.png">

**Comment by echosa** [comment]
Also, I did check the "Language Defaults" that are being inherited. No italics there at all. The box isn't checked *and* the text displays normally.

**Comment by arcticicestudio** [comment]
Thanks for your report 👍 
I've also been affected by this some time ago. It is related to the way IntelliJ imports the files. It is a bug which has already been reported to the official IntelliJ bug tracker, but unfortunately I forgot to note down the ticket ID.

If you untick the *Use inhertited declaration* option, *Apply* the changes and then tick the option again it will curiously load the correct settings from the theme 😕 

I also planned to update the theme in the near future to support the latest `2017.x` version which comes with some new syntax- and UI color definitions I'd like to add. This will also update the color theme XML version they use internally which may fix this problem.

Have you tried to install the theme using the settings JAR import method or copied it manually to the color directory? I believe I've only had import problems when using the copy method, the JAR imort should work fine.

**Comment by echosa** [comment]
> If you untick the Use inhertited declaration option, Apply the changes and then tick the option again it will curiously load the correct settings from the theme

I thought I tried that. I'll try again and see what happens.

> Have you tried to install the theme using the settings JAR import method or copied it manually to the color directory? 

I manually placed the .icls file into the colors directory. I'll remove it and try importing the JAR instead, after I try the other workaround, just to see if it works.

Thanks!

**Comment by echosa** [comment]
Update: neither method solved the issue. I'm using IDEA 2017.1, in case it matters. I tried unticking/re-ticking the the inherit checkbox for function declarations, applying the changes each time. That didn't work. I closed IDEA, deleted the icls file, and imported from the JAR. Everything is still italicized. :-/

Any other thoughts?

**Comment by arcticicestudio** [comment]
So it seems like they changed the import algorithm. Only solution might be to test it again as soon as I've implemented support for the new 2017.1 color theme features.
I'll @-mention you in the issue so you can check if it works.

**Comment by echosa** [comment]
Great. Thanks! I really nice this theme! I'm glad I found it. This is the first theme that's ever had a chance and taking me away from solarized dark. :-)

**Comment by pemedina** [comment]
I was having the same issue. While playing with different settings i was able to solve it like this:
![captura de pantalla 2017-04-12 a las 12 01 35 a m](https://cloud.githubusercontent.com/assets/2750254/24939440/af12f2bc-1f13-11e7-928a-4f58d7dac550.png)

This fixed both PHP and blade && smarty templates.

**Comment by echosa** [comment]
I just tried this, and it does seem to work. :+1:

**Comment by arcticicestudio** [comment]
👍 Thanks for investigating.
I think the *Template language* entry has ben added in some of the new releases and the theme does not support it yet so it used the default settings. I've added it to the list of update TODOs.

**Comment by arcticicestudio** [comment]
🚢 Shipped with release version 🏷 [0.2.0](https://github.com/arcticicestudio/nord-intellij-idea-syntax/releases/tag/v0.2.0).

**Comment by echosa** [comment]
Awesome. Thanks! I'll check it out later this week!
